import { ScreenUtils } from "@helpers";
import { Themes } from "@themes";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  generalInfo: {
    flexDirection: "column",
    justifyContent: "flex-start",
  },
  generalTab: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "flex-start",
    paddingTop: ScreenUtils.scale(24),
    backgroundColor: Themes.colors.white,
  },
  generalInfoRow: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    paddingHorizontal: ScreenUtils.scale(20),
    marginBottom: ScreenUtils.scale(20),
  },
  labelInfo: {
    ...Themes.font.medium,
    fontSize: 14,
    color: Themes.colors.textPrimary,
  },
  serviceButton: {
    paddingHorizontal: ScreenUtils.scale(16),
    paddingVertical: ScreenUtils.scale(13),
    borderColor: Themes.colors.colGray20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  inputInfo: {
    flex: 1,
    paddingHorizontal: ScreenUtils.scale(10),
    paddingVertical: ScreenUtils.scale(5),
    marginHorizontal: ScreenUtils.scale(5),
    borderColor: Themes.colors.colGray20,
    flexDirection: "row",
    alignItems: "center",
  },
  flex1: {
    flex: 1,
  },
  confirmPaymentBtn: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Themes.colors.bg,
    marginTop: ScreenUtils.scale(10),
    width: ScreenUtils.WIDTH - ScreenUtils.scale(40),
    borderRadius: ScreenUtils.scale(24),
  },
  confirmPaymentText: {
    ...Themes.font.medium,
    color: Themes.colors.white,
    fontSize: 14,
  },
  contentInfo: {
    ...Themes.font.bold,
  },
  shipmentContainer: {
    flexDirection: "column",
    borderWidth: 1,
    marginHorizontal: ScreenUtils.scale(20),
    padding: ScreenUtils.scale(16),
    marginBottom: ScreenUtils.scale(12),
    borderColor: Themes.colors.colGray20,
    borderRadius: ScreenUtils.scale(15),
    backgroundColor: Themes.colors.white,
  },
  subShipmentContainer: {
    flexDirection: "column",
    borderWidth: 1,
    margin: ScreenUtils.scale(10),
    padding: ScreenUtils.scale(10),
    borderColor: Themes.colors.colGray20,
    borderRadius: ScreenUtils.scale(10),
  },
  shipment: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  serviceSelect: {
    borderBottomWidth: 1,
    marginHorizontal: ScreenUtils.scale(20),
    paddingVertical: ScreenUtils.scale(17),
    borderColor: Themes.colors.colGray20,
    flexDirection: "row",
    alignItems: "center",
  },
  bottomModal: {
    maxHeight: "100%",
  },
  shipmentConfirm: {
    borderWidth: 1,
    marginHorizontal: ScreenUtils.scale(15),
    marginTop: ScreenUtils.scale(20),
    paddingHorizontal: ScreenUtils.scale(10),
    paddingVertical: ScreenUtils.scale(10),
    borderColor: Themes.colors.colGray20,
    borderRadius: ScreenUtils.scale(10),
  },
  codView: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginTop: ScreenUtils.scale(10),
  },
  totalCOD: {
    marginLeft: ScreenUtils.scale(15),
    ...Themes.font.bold,
    fontSize: 18,
  },
  modal: {
    flex: 1,
    backgroundColor: Themes.colors.white,
    flexDirection: "column",
    justifyContent: "flex-end",
  },
  hView: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignContent: "stretch",
    marginTop: ScreenUtils.scale(4),
    borderWidth: 1,
    borderColor: Themes.colors.colGray20,
    borderRadius: ScreenUtils.scale(15),
  },
  customerButton: {
    paddingHorizontal: ScreenUtils.scale(16),
    paddingVertical: ScreenUtils.scale(13),
    borderColor: Themes.colors.colGray20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: ScreenUtils.scale(15),
    marginTop: ScreenUtils.scale(4),
  },
  currencyButton: {
    paddingHorizontal: ScreenUtils.scale(16),
    paddingVertical: ScreenUtils.scale(13),
    borderColor: Themes.colors.colGray20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderLeftWidth: 1,
  },
  moneyIcon: {
    alignSelf: "center",
    marginLeft: ScreenUtils.scale(16),
  },
  optionView: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: ScreenUtils.scale(24),
  },
  cameraView: {
    width: ScreenUtils.scale(48),
    height: ScreenUtils.scale(48),
    borderWidth: 1,
    borderColor: Themes.colors.colGray20,
    borderRadius: ScreenUtils.scale(24),
    justifyContent: "center",
    alignItems: "center",
  },
  viewDocumentButton: {
    borderWidth: 1,
    borderColor: Themes.colors.colGray20,
    borderRadius: ScreenUtils.scale(24),
    justifyContent: "center",
    alignItems: "center",
    height: ScreenUtils.scale(48),
    paddingHorizontal: ScreenUtils.scale(20),
    marginLeft: ScreenUtils.scale(25),
  },
  shipments: {
    marginTop: ScreenUtils.scale(20),
  },
  shipmentNumber: {
    fontWeight: "600",
    color: Themes.colors.coolGray100,
  },
  shipmentStatus: {
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: ScreenUtils.scale(99),
    paddingHorizontal: ScreenUtils.scale(6),
    paddingVertical: ScreenUtils.scale(2),
  },
  infoText: {
    fontWeight: "400",
    color: Themes.colors.coolGray100,
  },
  shipmentInfo: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: ScreenUtils.scale(5),
  },
  iconShipment: {
    flexDirection: "row",
    width: ScreenUtils.scale(25),
    justifyContent: "flex-start",
    alignItems: "center",
  },
  optionName: {
    marginLeft: ScreenUtils.scale(8),
  },
  qrUserManual: {
    fontSize: 18,
    fontWeight: "600",
  },
  headerBottomSheet: {
    paddingHorizontal: ScreenUtils.scale(20),
    paddingVertical: ScreenUtils.scale(10),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
});
