import { ScreenUtils } from "@helpers";
import { Themes } from "@themes";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  tabBar: {
    backgroundColor: Themes.colors.bP60,
    marginTop: ScreenUtils.calculatorHeight(10),
  },
  labelStyle: {
    ...Themes.font.bold,
    fontSize: 14,
    color: Themes.colors.white,
  },
  indicatorStyle: {
    backgroundColor: Themes.colors.white,
  },
  tabContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    paddingTop: ScreenUtils.calculatorHeight(20),
  },
  generalInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: ScreenUtils.calculatorHeight(12),
    borderBottomWidth: 1,
    borderBottomColor: Themes.colors.colGray20,
  },
  labelInfo: {
    ...Themes.font.medium,
    fontSize: 14,
    color: Themes.colors.coolGray100,
    fontWeight: "400",
  },
  contentInfo: {
    ...Themes.font.medium,
    fontSize: 14,
    color: Themes.colors.coolGray60,
    fontWeight: "400",
  },
  inputInfo: {
    borderWidth: 1,
    paddingHorizontal: ScreenUtils.calculatorWidth(10),
    paddingVertical: ScreenUtils.calculatorHeight(5),
    marginRight: ScreenUtils.calculatorWidth(8),
    borderColor: Themes.colors.collGray40,
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    maxWidth: ScreenUtils.calculatorWidth(100),
  },
  serviceSelect: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingVertical: ScreenUtils.calculatorHeight(12),
    borderBottomWidth: 1,
    borderBottomColor: Themes.colors.colGray20,
    marginHorizontal: ScreenUtils.calculatorWidth(20),
  },
  serviceButton: {
    paddingVertical: ScreenUtils.calculatorHeight(5),
    marginHorizontal: ScreenUtils.calculatorWidth(5),
    borderColor: Themes.colors.collGray40,
    flexDirection: "row",
    alignItems: "center",
  },
  contentTab: {
    marginTop: ScreenUtils.calculatorHeight(27),
  },
  itemInfoContainer: {
    flexDirection: "column",
    alignItems: "stretch",
    borderWidth: 1,
    marginHorizontal: ScreenUtils.calculatorWidth(20),
    marginBottom: ScreenUtils.calculatorHeight(10),
    borderColor: Themes.colors.colGray20,
    borderRadius: ScreenUtils.calculatorWidth(15),
    backgroundColor: Themes.colors.white,
  },
  images: {
    width: 100,
    height: 100,
  },
  serviceInfoContainer: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    marginHorizontal: ScreenUtils.calculatorWidth(20),
    padding: ScreenUtils.calculatorHeight(16),
    backgroundColor: Themes.colors.white,
    marginBottom: ScreenUtils.calculatorHeight(12),
    borderRadius: ScreenUtils.calculatorHeight(15),
  },
  infoItem: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    marginLeft: ScreenUtils.calculatorWidth(10),
  },
  serviceLabel: {
    ...Themes.font.medium,
    fontSize: 13,
    color: Themes.colors.textPrimary,
    marginRight: ScreenUtils.calculatorWidth(8),
    fontWeight: "700",
  },
  button: {
    width: ScreenUtils.calculatorWidth(40),
    height: ScreenUtils.calculatorWidth(40),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Themes.colors.colGray20,
    borderRadius: ScreenUtils.calculatorWidth(20),
    marginRight: ScreenUtils.calculatorWidth(12),
  },
  hView: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  hitSlop: {
    top: 10,
    bottom: 10,
    left: 10,
    right: 10,
  },
  shipmentContainer: {
    flexDirection: "column",
    borderWidth: 1,
    margin: ScreenUtils.calculatorWidth(10),
    padding: ScreenUtils.calculatorHeight(10),
    borderColor: Themes.colors.collGray40,
    borderRadius: ScreenUtils.calculatorWidth(10),
  },
  subShipmentContainer: {
    flexDirection: "column",
    marginHorizontal: ScreenUtils.calculatorWidth(20),
    padding: ScreenUtils.calculatorHeight(16),
    borderColor: Themes.colors.collGray40,
    borderRadius: ScreenUtils.calculatorWidth(15),
    backgroundColor: Themes.colors.white,
    marginBottom: ScreenUtils.calculatorHeight(13),
  },
  logoutContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  logoutTitle: {
    ...Themes.font.bold,
    fontSize: 18,
    color: Themes.colors.textPrimary,
    marginBottom: ScreenUtils.calculatorHeight(15),
  },
  generalTab: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "flex-start",
  },
  generalInfo: {
    flexDirection: "column",
    justifyContent: "flex-start",
    backgroundColor: Themes.colors.white,
    marginTop: ScreenUtils.calculatorHeight(20),
    marginHorizontal: ScreenUtils.calculatorWidth(20),
    paddingVertical: ScreenUtils.calculatorHeight(16),
    paddingHorizontal: ScreenUtils.calculatorWidth(16),
    borderRadius: ScreenUtils.calculatorHeight(15),
    marginBottom: ScreenUtils.calculatorHeight(20),
  },
  updateButton: {
    minWidth: ScreenUtils.WIDTH - ScreenUtils.calculatorWidth(40),
    marginVertical: ScreenUtils.calculatorHeight(20),
    height: ScreenUtils.calculatorHeight(48),
    backgroundColor: Themes.colors.bg,
  },
  addServiceBtn: {
    marginVertical: ScreenUtils.calculatorHeight(20),
  },
  bottomModal: {
    maxHeight: "100%",
    paddingBottom: ScreenUtils.calculatorHeight(10),
  },
  loadingView: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  spaceBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingRight: ScreenUtils.calculatorWidth(10),
  },
  addMorePiece: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    marginHorizontal: ScreenUtils.calculatorWidth(20),
    paddingVertical: ScreenUtils.calculatorHeight(16),
    borderRadius: ScreenUtils.calculatorWidth(25),
    borderColor: Themes.colors.collGray40,
    borderStyle: "dashed",
  },
  addMorePieceText: {
    ...Themes.font.medium,
    fontSize: 14,
    color: Themes.colors.brand60,
    marginLeft: ScreenUtils.calculatorWidth(10),
  },
  shipment: {
    flexDirection: "row",
    alignItems: "center",
  },
  enterCode: {
    borderBottomWidth: 1,
    marginHorizontal: ScreenUtils.calculatorWidth(20),
    marginBottom: ScreenUtils.calculatorHeight(33),
    paddingVertical: ScreenUtils.calculatorHeight(12),
    borderColor: Themes.colors.colGray20,
  },
  qrUserManual: {
    fontSize: 18,
    fontWeight: "600",
  },
  headerBottomSheet: {
    paddingHorizontal: ScreenUtils.calculatorWidth(20),
    paddingVertical: ScreenUtils.calculatorHeight(10),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  switch: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  subShipmentPiece: {
    fontWeight: "600",
    color: Themes.colors.brand60,
    marginBottom: ScreenUtils.calculatorHeight(12),
  },
  deletePiece: {
    position: "absolute",
    top: -5,
    right: -5,
  },
  rowEnd: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  checkIcon: {
    width: ScreenUtils.calculatorWidth(16),
    height: ScreenUtils.calculatorWidth(16),
    borderWidth: 1,
    borderRadius: ScreenUtils.calculatorWidth(8),
    marginRight: ScreenUtils.calculatorWidth(8),
  },
  contentInfoRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingVertical: ScreenUtils.calculatorHeight(14),
    borderBottomWidth: 1,
    borderBottomColor: Themes.colors.colGray20,
    paddingHorizontal: ScreenUtils.calculatorWidth(16),
  },
  infoText: {
    marginLeft: ScreenUtils.calculatorWidth(8),
  },
  contentChild: {
    flex: 0.5,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: Themes.colors.colGray20,
    paddingVertical: ScreenUtils.calculatorHeight(14),
    paddingHorizontal: ScreenUtils.calculatorHeight(16),
  },
  bottomRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  checkbox: {
    marginRight: ScreenUtils.calculatorWidth(8),
  },
  optionView: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: ScreenUtils.calculatorHeight(20),
  },
  flex1: {
    flex: 1,
  },
  viewImage: {
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Themes.colors.colGray20,
    height: ScreenUtils.calculatorWidth(40),
    paddingHorizontal: ScreenUtils.calculatorWidth(30),
    borderRadius: ScreenUtils.calculatorHeight(99),
  },
  locationButton: {
    flexDirection: "row",
    alignItems: "center",
  },
});
