import { ScreenUtils } from "@helpers";
import { Themes } from "@themes";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Themes.colors.transparentBlack,
  },
  scrollViewContainer: {
    maxHeight: ScreenUtils.HEIGHT / 2,
    width: "90%",
  },
  content: {
    backgroundColor: Themes.colors.white,
    marginHorizontal: ScreenUtils.scale(24),
    paddingHorizontal: ScreenUtils.scale(8),
    paddingVertical: ScreenUtils.scale(16),
    borderRadius: ScreenUtils.scale(8),
  },
  title: {
    ...Themes.font.medium,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "700",
    color: Themes.colors.coolGray100,
    textAlign: "center",
  },
  message: {
    fontSize: 14,
    lineHeight: 16,
    fontWeight: "500",
    textAlign: "center",
    marginVertical: ScreenUtils.scale(12),
  },
  confirm: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: ScreenUtils.scale(16),
  },
  button: {
    flex: 1,
    marginHorizontal: ScreenUtils.scale(4),
    paddingVertical: ScreenUtils.scale(8),
    borderRadius: ScreenUtils.scale(8),
    borderWidth: 2 * StyleSheet.hairlineWidth,
    backgroundColor: Themes.colors.white,
    borderColor: Themes.colors.info60,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonCancel: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
    color: Themes.colors.info60,
  },
  buttonChild: {
    flex: 1,
    marginHorizontal: ScreenUtils.scale(4),
    paddingVertical: ScreenUtils.scale(8),
    borderRadius: ScreenUtils.scale(8),
    borderWidth: 2 * StyleSheet.hairlineWidth,
    backgroundColor: Themes.colors.info60,
    borderColor: Themes.colors.info60,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonSubmit: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
    color: Themes.colors.white,
  },
  icon: {
    alignSelf: "center",
    marginVertical: ScreenUtils.scale(12),
  },
  hitSlop: {
    top: 20,
    bottom: 20,
    left: 20,
    right: 20,
  },
  radioButton: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: ScreenUtils.scale(8),
    marginHorizontal: ScreenUtils.scale(8),
  },
  rateItemContainer: {
    width: ScreenUtils.scale(16),
    height: ScreenUtils.scale(16),
    borderRadius: ScreenUtils.scale(8),
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    marginRight: ScreenUtils.scale(8),
  },
  circleCheckedContainer: {
    width: ScreenUtils.scale(8),
    height: ScreenUtils.scale(8),
    borderRadius: ScreenUtils.scale(4),
    backgroundColor: Themes.colors.primary,
  },
  check: {
    borderWidth: 2,
    borderColor: Themes.colors.primary,
  },
  uncheck: {
    borderWidth: 2,
    borderColor: Themes.colors.collGray40,
  },
  buttonRateText: {
    ...Themes.font.medium,
    fontSize: 14,
    color: Themes.colors.textPrimary,
  },
  input: {
    borderWidth: 1,
    borderColor: Themes.colors.colGray20,
    borderRadius: ScreenUtils.scale(8),
    marginTop: ScreenUtils.scale(8),
    marginHorizontal: ScreenUtils.scale(8),
    paddingHorizontal: ScreenUtils.scale(12),
    height: ScreenUtils.scale(48),
  },
  error: {
    ...Themes.font.medium,
    fontSize: 12,
    lineHeight: 18,
    color: Themes.colors.danger60,
    marginTop: ScreenUtils.scale(4),
    marginHorizontal: ScreenUtils.scale(8),
  },
});
