export const Images = {
  lockedAccount: require("../assets/images/lockedAccount.png"),
  qrIcon: require("../assets/lottie/qr_icon.json"),
  qrIconFill: require("../assets/lottie/qr_icon_fill.json"),
  productDefault: require("../assets/images/defaultProduct.png"),
  headerImage: require("../assets/images/header_image.png"),
  splashImage: require("../assets/images/splash_image.png"),
  checkAndScan: require("../assets/icons/check_and_scan.png"),
  cod: require("../assets/icons/cod.png"),
  shipmentManagement: require("../assets/icons/shipment_management.png"),
  claimAndInquiries: require("../assets/icons/claim_and_require.png"),
  efexImage: require("../assets/icons/efex.png"),
  icMenuHome: require("../assets/icons/ic_menu_home.png"),
  icMenuScanAndCheck: require("../assets/icons/ic_menu_scan_check.png"),
  icMenuScanCod: require("../assets/icons/ic_menu_scan_cod.png"),
  icMenuShipmentManage: require("../assets/icons/ic_menu_shipment_manage.png"),
  icMenuClaim: require("../assets/icons/ic_menu_claim.png"),
  icMenuSetting: require("../assets/icons/ic_menu_setting.png"),
  icMenuUser: require("../assets/icons/ic_menu_user.png"),
  icTakePhoto: require("../assets/icons/ic_take_photo.png"),
  icLocation: require("../assets/icons/doivitri.png"),
  icExploit: require("../assets/icons/khieunai.png"),
  icInventory: require("../assets/icons/kiemke.png"),
  icPicking: require("../assets/icons/pcking.png"),
  noData: require("../assets/images/no_data.png"),
};

export const Loader = {
  launchLoader: require("../assets/lottie/launch-loader.json"),
};
