export enum ShipmentInfoActionType {
  GET_ALL_SHIPMENT_SERVICE = "GET_ALL_SHIPMENT_SERVICE",
  GET_ALL_SHIPPING_METHOD = "GET_ALL_SHIPPING_METHOD",
  GET_ALL_SHIPMENT_ADD_SERVICE = "GET_ALL_SHIPMENT_ADD_SERVICE",
  GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER",
  GET_ALL_CURRENCY = "GET_ALL_CURRENCY",
}
